#!/usr/bin/env python3
"""Convallaria project maintenance CLI."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CLAUDE_TARGET = ROOT / ".claude"
CLAUDE_COMMAND_SOURCE = ROOT / "claude" / "commands"
USER_CLAUDE_TARGET = Path.home() / ".claude"
PERSONAL_MARKETPLACE = Path.home() / ".agents" / "plugins" / "marketplace.json"
PERSONAL_PLUGIN_LINK = Path.home() / "plugins" / "convallaria"
MANAGED_MARKER = "<!-- Generated by Convallaria; edit the source checkout instead. -->"


def run(command: list[str]) -> int:
    return subprocess.run(command, cwd=ROOT).returncode


def cmd_sync(args: argparse.Namespace) -> int:
    command = ["python3", str(ROOT / "scripts" / "update_convallaria.py")]
    if getattr(args, "codex_cachebuster", False):
        command.append("--codex-cachebuster")
    if args.no_codex_cachebuster:
        command.append("--no-codex-cachebuster")
    if getattr(args, "codex_marketplace", False):
        command.append("--codex-marketplace")
    if getattr(args, "force_codex_marketplace", False):
        command.append("--force-codex-marketplace")
    if args.no_claude_sync:
        command.append("--no-claude-sync")
    if getattr(args, "claude_scope", None):
        command.extend(["--claude-scope", args.claude_scope])
    if args.dry_run:
        command.append("--dry-run")
    if args.smoke:
        command.append("--smoke")
    if args.skip_raster:
        command.append("--skip-raster")
    return run(command)


def cmd_doctor(args: argparse.Namespace) -> int:
    command = ["python3", str(ROOT / "scripts" / "smoke_test.py")]
    if args.skip_raster:
        command.append("--skip-raster")
    return run(command)


def cmd_install(args: argparse.Namespace) -> int:
    print("Convallaria install prepares Claude Code commands and the local Codex marketplace entry.", flush=True)
    if args.project_only:
        args.claude_scope = "project"
        args.codex_marketplace = False
    else:
        args.claude_scope = "both"
        args.codex_marketplace = True
    return cmd_sync(args)


def remove_if_generated(path: Path, source: Path | None = None) -> bool:
    if not path.exists() or not path.is_file():
        return False
    if source is not None and source.exists():
        if path.read_text(encoding="utf-8") != source.read_text(encoding="utf-8"):
            return False
    path.unlink()
    return True


def remove_if_managed(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    if MANAGED_MARKER not in path.read_text(encoding="utf-8"):
        return False
    path.unlink()
    return True


def remove_personal_marketplace_entry() -> bool:
    if not PERSONAL_MARKETPLACE.exists():
        return False
    data = json.loads(PERSONAL_MARKETPLACE.read_text(encoding="utf-8"))
    plugins = data.get("plugins", [])
    if not isinstance(plugins, list):
        return False
    kept = [
        plugin
        for plugin in plugins
        if not (
            isinstance(plugin, dict)
            and plugin.get("name") == "convallaria"
            and isinstance(plugin.get("source"), dict)
            and plugin["source"].get("source") == "local"
            and plugin["source"].get("path") == "./plugins/convallaria"
        )
    ]
    if len(kept) == len(plugins):
        return False
    data["plugins"] = kept
    PERSONAL_MARKETPLACE.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return True


def remove_personal_plugin_link() -> bool:
    if not PERSONAL_PLUGIN_LINK.is_symlink():
        return False
    if PERSONAL_PLUGIN_LINK.resolve() != ROOT.resolve():
        return False
    PERSONAL_PLUGIN_LINK.unlink()
    return True


def cmd_uninstall(args: argparse.Namespace) -> int:
    removed = []
    guide = CLAUDE_TARGET / "CLAUDE.md"
    if remove_if_generated(guide, ROOT / "CLAUDE.md"):
        removed.append(guide)

    command_target = CLAUDE_TARGET / "commands"
    for source in sorted(CLAUDE_COMMAND_SOURCE.glob("*.md")):
        target = command_target / source.name
        if remove_if_generated(target, source):
            removed.append(target)

    if command_target.exists() and not any(command_target.iterdir()):
        command_target.rmdir()
    if CLAUDE_TARGET.exists() and not any(CLAUDE_TARGET.iterdir()):
        CLAUDE_TARGET.rmdir()

    user_command_target = USER_CLAUDE_TARGET / "commands"
    for source in sorted(CLAUDE_COMMAND_SOURCE.glob("*.md")):
        target = user_command_target / source.name
        if remove_if_managed(target):
            removed.append(target)

    if remove_personal_marketplace_entry():
        removed.append(PERSONAL_MARKETPLACE)
    if remove_personal_plugin_link():
        removed.append(PERSONAL_PLUGIN_LINK)

    for path in removed:
        try:
            label = path.relative_to(ROOT)
        except ValueError:
            label = path
        print(f"removed: {label}")
    if not removed:
        print("ok: no generated Convallaria Claude Code files were removed")

    print("next: remove any installed Codex runtime copy with the matching Codex plugin remove command if your Codex CLI/app keeps one")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    install = subparsers.add_parser("install", help="Prepare local Codex and Claude Code integrations.")
    install.add_argument("--dry-run", action="store_true")
    install.add_argument("--smoke", dest="smoke", action="store_true", help="Run the smoke test after installing.")
    install.add_argument("--no-smoke", dest="smoke", action="store_false", help="Skip the smoke test after installing.")
    install.set_defaults(smoke=True)
    install.add_argument("--skip-raster", action="store_true")
    install.add_argument("--codex-cachebuster", action="store_true", help="Update plugin.json with a local Codex cachebuster before reinstalling.")
    install.add_argument("--no-codex-cachebuster", action="store_true")
    install.add_argument("--force-codex-marketplace", action="store_true", help="Replace an existing convallaria entry in the personal Codex marketplace.")
    install.add_argument("--no-claude-sync", action="store_true")
    install.add_argument("--project-only", action="store_true", help="Only sync project-local .claude files and skip user-level Claude/Codex installation.")
    install.set_defaults(func=cmd_install)

    sync = subparsers.add_parser("sync", help="Refresh generated local integration surfaces.")
    sync.add_argument("--dry-run", action="store_true")
    sync.add_argument("--smoke", action="store_true")
    sync.add_argument("--skip-raster", action="store_true")
    sync.add_argument("--codex-cachebuster", action="store_true", help="Update plugin.json with a local Codex cachebuster before reinstalling.")
    sync.add_argument("--no-codex-cachebuster", action="store_true")
    sync.add_argument("--codex-marketplace", action="store_true", help="Create or update the default personal Codex marketplace entry.")
    sync.add_argument("--force-codex-marketplace", action="store_true", help="Replace an existing convallaria entry in the personal Codex marketplace.")
    sync.add_argument("--no-claude-sync", action="store_true")
    sync.add_argument(
        "--claude-scope",
        choices=["project", "user", "both"],
        default="project",
        help="Which Claude Code command surfaces to sync.",
    )
    sync.set_defaults(func=cmd_sync)

    update = subparsers.add_parser("update", help="Alias for sync with a smoke test.")
    update.add_argument("--dry-run", action="store_true")
    update.add_argument("--smoke", dest="smoke", action="store_true", help="Run the smoke test after updating.")
    update.add_argument("--no-smoke", dest="smoke", action="store_false", help="Skip the smoke test after updating.")
    update.set_defaults(smoke=True)
    update.add_argument("--skip-raster", action="store_true")
    update.add_argument("--codex-cachebuster", action="store_true", help="Update plugin.json with a local Codex cachebuster before reinstalling.")
    update.add_argument("--no-codex-cachebuster", action="store_true")
    update.add_argument("--codex-marketplace", action="store_true", help="Create or update the default personal Codex marketplace entry.")
    update.add_argument("--force-codex-marketplace", action="store_true", help="Replace an existing convallaria entry in the personal Codex marketplace.")
    update.add_argument("--no-claude-sync", action="store_true")
    update.add_argument(
        "--claude-scope",
        choices=["project", "user", "both"],
        default="project",
        help="Which Claude Code command surfaces to sync.",
    )
    update.set_defaults(func=cmd_sync)

    doctor = subparsers.add_parser("doctor", help="Run the Convallaria smoke test.")
    doctor.add_argument("--skip-raster", action="store_true")
    doctor.set_defaults(func=cmd_doctor)

    uninstall = subparsers.add_parser("uninstall", help="Remove generated local Claude Code adapters for Convallaria.")
    uninstall.set_defaults(func=cmd_uninstall)

    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
